server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  datasource:
    url:  jdbc:mysql://localhost/movie
    username: uehara
    password: password
    driverClassName: com.mysql.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 159187919691-oe7i6r0nkfnl96bk6gl2sleskviu43c7.apps.googleusercontent.com
            client-secret: AvpIsmfQ_QRZryy6qyYk29Il
            
            